---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove unused dependencies"
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create web dir"
  file:
    path: ~/web
    state: directory

- name: "copy index script"
  template:
    src: files/index.js
    dest: ~/web/index.js

- name: "Start the web server"
  shell: |
    pm2 start ~/web/index.js -f
